name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        user: eoscostarica
        filename: profile/metrics.svg
        token: ${{ secrets.GITHUB_TOKEN }}
        base: header, activity, metadata
        plugin_followup: yes
        plugin_followup_sections: repositories
        plugin_languages: yes