name: Metrics

on:
  schedule:
    - cron: '0 0 29 2 1'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        user: eoscostarica
        filename: profile/metrics.svg
        token: ${{ secrets.GITHUB_TOKEN }}
        base: activity
        plugin_followup: yes
        plugin_followup_sections: repositories
        plugin_followup_indepth: yes
